version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    restart: always
  db:
    image: mysql
    volumes:
      - ./db-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=mydb
    ports:
      - 3306:3306
    restart: unless-stopped

volumes:
  db-data:
